# -*- coding: utf-8 -*-
"""HR Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zmkt4PAhGH45NTSF14dzeGo5fRAiGdKg
"""

from contextlib import suppress
import mailbox
import re
import os
!pip install xlsxwriter
import xlsxwriter
from google.colab import drive
import zipfile
drive.mount('/content/drive')

import zipfile
os.chdir("/content/drive/My Drive/Takeout/")
#Extracting ZIp
extension = ".zip"
for item in os.listdir(os.getcwd()): # loop through items in dir
    if item.endswith(extension): # check for ".zip" extension
        file_name = os.path.abspath(item) # get full path of files
        zip_ref = zipfile.ZipFile(file_name) # create zipfile object
        zip_ref.extractall(os.getcwd()) # extract file to dir
        zip_ref.close() # close file

"""Append mails to a list"""

a= [] 
for m in mailbox.mbox("/content/drive/My Drive/Takeout/Takeout/Mail/Trash.mbox"):
    with suppress(KeyError):
        mstring = m.as_string()
        a.append(mstring)

"""Append email ids to a list"""

mail1 = []
for i in range(len(a)):
    s = re.findall(r'[\s|\<]\w+\.?\_?\w*\@\w*\-?\.?\w*\.?\w*\.\w+',a[i])
    for i in range(len(s)):
        mail1.append(s[i])

"""Remove garbage charcters"""

mail = []
for i in range(len(mail1)):
    s = re.findall(r'\w+\.?\_?\w*\@\w*\-?\.?\w*\.?\w*\.\w+',mail1[i])
    for i in range(len(s)):
        mail.append(s[i])

import pandas as pd
mail2 = pd.DataFrame(mail)
mail2.to_excel('HRA7.xlsx')

"""Change directory for obtaining output

Get all emails in an excel file
"""

xbook = xlsxwriter.Workbook('HRA6.xlsx')
xsheet = xbook.add_worksheet('HR_1')
xsheet.write_row(0,0,mail2)
xbook.close()

"""Getting emails from text file"""